# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Delphine Chadefaux
email: delphine.chadefaux@sorbonne-paris-nord.fr
description: >- # this means to ignore newlines until "baseurl:"
  Maître de conférences en biomécanique de la performance ; Université Sorbonne Paris Nord ; Institut de Biomécanique Humaine Georges Charpak.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  DChadefaux
#icon: ⚛️  # the emoji used as the favicon (alternatively, provide image name in /assets/img/)
icon: assets/img/DChadefaux_Photo.jpg

#domain: my-site.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
#url: https://my-site.github.io  # the base hostname and protocol for your site, e.g. http://example.com
#baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed


# Sitemap settings
defaults:
  - scope:
      path: "assets"
    values:
      sitemap: false

sass:
  style: compressed


# -----------------------------------------------------------------------------
# Responsive WebP Images
# -----------------------------------------------------------------------------

imagemagick:
  enabled: true # enables responsive images for your site (recommended, see https://github.com/alshedivat/al-folio/issues/537)
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - "/mnt/FCB42A31B429EF38/DChadefaux_OneDrive/DChadefaux.github.io
/assets/img/"
  input_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".tiff"
  output_formats:
    webp: "-resize 800x"



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
